#/***************************************************************************
#
# QGIS Python Documentation Generator
#                             -------------------
#        begin                : 2017-04-14
#        copyright            : (C) 2017 by Tim Sutton
#        email                : tim@qgis.org
# ***************************************************************************/
#
#/***************************************************************************
# *                                                                         *
# *   This program is free software; you can redistribute it and/or modify  *
# *   it under the terms of the GNU General Public License as published by  *
# *   the Free Software Foundation; either version 2 of the License, or     *
# *   (at your option) any later version.                                   *
# *                                                                         *
# ***************************************************************************/

#
# Original Makefile generated by Sphinx
#

# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    = -T -j auto
SPHINXBUILD   = sphinx-build
SPHINXPROJ    = QGIS
QGIS_VERSION   = master
BUILDDIR      = build/${QGIS_VERSION}
SOURCEDIR     = api/${QGIS_VERSION}

# Following variables should be sent when making
# QGISVERSION might be override by doing make prepare QGISVERSION=3.2
# SPHINX_RTD_EGG_PATH can be used to provide a custom version of sphinx_rtd_theme to support versioning

OS := $(shell uname)
ifeq ($(OS), Darwin)
  SED = 'gsed'
else
  SED = 'sed'
endif

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -c $(SOURCEDIR) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

prepare:
	${SED} -r 's/__QGIS_VERSION__/${QGIS_VERSION}/g;' conf.in.py > $(SOURCEDIR)/conf.py

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
