import inspect
import re
from enum import Enum

from sphinx.ext.autodoc import MethodDocumenter


class OverloadedPythonMethodDocumenter(MethodDocumenter):
    """
    A method documenter which handles overloaded methods, via processing
    the docstrings generated by SIP
    """

    objtype = "method"
    priority = MethodDocumenter.priority

    @classmethod
    def can_document_member(cls, member, membername, isattr, parent):
        return MethodDocumenter.can_document_member(member, membername, isattr, parent)

    @staticmethod
    def parse_signature_blocks(docstring):
        """
        Extracts each signature from a sip generated docstring, and
        returns each signature in a tuple with the docs for just
        that signature.
        """

        class SignaturePart(Enum):
            Leading = 0
            Arguments = 1
            ReturnType = 2

        res = []
        current_sig = ""
        current_desc = ""
        for line in docstring.split("\n"):
            leading = ""
            arguments = ""
            return_type = ""
            part = SignaturePart.Leading
            depth = 0
            is_signature = True
            # try to find out if this line is a signature, and if so, extract
            # its components.
            # we can't use a regular expression for this, as we need to account
            # for potentially nested () [] in the arguments lists...
            for char in line:
                if part == SignaturePart.Leading and char == " ":
                    is_signature = False
                    break
                if part == SignaturePart.Leading and char != "(":
                    leading += char
                elif part == SignaturePart.Leading and char == "(":
                    part = SignaturePart.Arguments
                    arguments += "("
                    depth = 1
                elif part == SignaturePart.Arguments and char not in ("(", ")", "[", "]"):
                    arguments += char
                elif part == SignaturePart.Arguments:
                    if char in ("(", "["):
                        depth += 1
                    if char in (")", "]"):
                        depth -= 1
                    arguments += char
                    if depth == 0:
                        part = SignaturePart.ReturnType
                elif part == SignaturePart.ReturnType:
                    return_type += char
            if (
                part != SignaturePart.ReturnType
                or not leading
                or not re.match(r"^[a-zA-Z0-9_]+$", leading)
            ):
                is_signature = False

            if is_signature:
                if current_sig:
                    res.append((current_sig, current_desc))
                current_sig = arguments + return_type
                current_desc = ""
            else:
                current_desc += line + "\n"

        if current_sig:
            res.append((current_sig, current_desc))

        return res

    def add_content(self, more_content):
        """
        Parse the docstring to get all signatures and their descriptions
        """
        sourcename = self.get_sourcename()
        docstring = inspect.getdoc(self.object)
        if docstring:
            # does this method have multiple overrides?
            signature_blocks = self.parse_signature_blocks(docstring)

            if len(signature_blocks) <= 1:
                # nope, just use standard formatter then!
                super().add_content(more_content)
                return

            # add a method output for EVERY override
            for i, (signature, description) in enumerate(signature_blocks):
                if i > 0:
                    self.add_line("", sourcename)

                # this pattern is used in the autodoc source!
                old_indent = self.indent
                new_indent = (
                    " "
                    * len(self.content_indent)
                    * (len(self.indent) // len(self.content_indent) - 1)
                )
                # skip the signature for the first overload. This will already
                # have been included by the base class Documenter logic!
                if i > 0:
                    self.indent = new_indent
                    self.add_directive_header(signature)
                    self.indent = old_indent
                    # we can only index the first signature!
                    self.add_line(":no-index:", sourcename)
                    self.add_line("", sourcename)

                doc_for_this_override = self.object_name + signature + "\n" + description
                for line in self.process_doc([doc_for_this_override.split("\n")]):
                    self.add_line(line, sourcename)
