name: Testing

on:
  pull_request:
  push:

jobs:

  test_builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Run docs builder tests
      run: |
        pip install -U pytest sphinx &&
        pytest
